### ISSUE TITLE
pgo.InternalCompilerError when generating Go implementation

### ISSUE THREAD

**Issue by shayanh** [UBC-NSS/pgo#127]
Consider this MPCal program:
```
--mpcal bug3 {
    macro mayFail() {
        if (EXPLORE_FAIL) {
            either {
                skip;
            } or {
                goto fail;
            };
        };
    };
    
    archetype AFoo() {
        start:
            mayFail();
        
        program:
            print("program");
            goto start;
        
        fail:
            print("fail");
    }
    
    fair process (Foo \in 1..NUM_NODES) == instance AFoo();
}
```

When I compile the mentioned program into Go implementation, I got the following error. Compiling to PlusCal works fine.
```
[error] (run-main-8) pgo.InternalCompilerError: internal compiler error
[error] pgo.InternalCompilerError: internal compiler error
[error] 	at pgo.trans.passes.codegen.go.CriticalSectionTracker.checkCompatibility(CriticalSectionTracker.java:96)
[error] 	at pgo.trans.passes.codegen.go.PlusCalStatementCodeGenVisitor.visit(PlusCalStatementCodeGenVisitor.java:141)
[error] 	at pgo.trans.passes.codegen.go.PlusCalStatementCodeGenVisitor.visit(PlusCalStatementCodeGenVisitor.java:20)
[error] 	at pgo.model.pcal.PlusCalIf.accept(PlusCalIf.java:43)
[error] 	at pgo.trans.passes.codegen.go.PlusCalStatementCodeGenVisitor.visit(PlusCalStatementCodeGenVisitor.java:66)
[error] 	at pgo.trans.passes.codegen.go.PlusCalStatementCodeGenVisitor.visit(PlusCalStatementCodeGenVisitor.java:20)
[error] 	at pgo.model.pcal.PlusCalLabeledStatements.accept(PlusCalLabeledStatements.java:34)
[error] 	at pgo.trans.passes.codegen.go.ModularPlusCalGoCodeGenPass.perform(ModularPlusCalGoCodeGenPass.java:275)
[error] 	at pgo.PGoMain.specToGoPipeline(PGoMain.java:252)
[error] 	at pgo.PGoMain.run(PGoMain.java:349)
[error] 	at pgo.PGoMain.main(PGoMain.java:69)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 1 s, completed May 12, 2021, 5:08:07 PM
```

**Comment by shayanh** [comment]
And here is the config file that I'm using for generating Go code:
```
{
  "build": {
    "output_dir": "/home/shayan/Documents/github/UBC-NSS/pgo-output",
    "dest_package": "bug"
  },
  "constants": {
    "NUM_NODES": "5",
    "EXPLORE_FAIL": "FALSE"
  }
}
```

**Comment by fhackett** [comment]
Quick question: was there a `NUM_NODES` definition in your original TLA+ file?

**Comment by shayanh** [comment]
Yes, I double checked it right now.
