### ISSUE TITLE
AssertionError when wrongly mapping a 2D array

### ISSUE THREAD

**Issue by shayanh** [UBC-NSS/pgo#163]
I got the following error when I want to compile the attached spec:
```
[error] (run-main-1) java.lang.AssertionError: assertion failed
[error] java.lang.AssertionError: assertion failed
[error] 	at scala.Predef$.assert(Predef.scala:265)
[error] 	at pgo.trans.MPCalPCalCodegenPass$.$anonfun$apply$10(MPCalPCalCodegenPass.scala:204)
[error] 	at scala.Option.flatMap(Option.scala:283)
[error] 	at pgo.trans.MPCalPCalCodegenPass$.pgo$trans$MPCalPCalCodegenPass$$applyMappingMacros$1(MPCalPCalCodegenPass.scala:199)
[error] 	at pgo.trans.MPCalPCalCodegenPass$.$anonfun$apply$18(MPCalPCalCodegenPass.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:293)
[error] 	at pgo.trans.MPCalPCalCodegenPass$.pgo$trans$MPCalPCalCodegenPass$$applyMappingMacros$1(MPCalPCalCodegenPass.scala:238)
[error] 	at pgo.trans.MPCalPCalCodegenPass$$anonfun$5.$anonfun$applyOrElse$12(MPCalPCalCodegenPass.scala:373)
[error] 	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:585)
[error] 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:599)
[error] 	at scala.collection.immutable.List.prependedAll(List.scala:152)
[error] 	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
[error] 	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
[error] 	at scala.collection.AbstractIterable.toList(Iterable.scala:919)
[error] 	at pgo.trans.MPCalPCalCodegenPass$$anonfun$5.applyOrElse(MPCalPCalCodegenPass.scala:373)
[error] 	at pgo.trans.MPCalPCalCodegenPass$$anonfun$5.applyOrElse(MPCalPCalCodegenPass.scala:327)
[error] 	at pgo.model.Rewritable$TopDownFirstStrategy$.execute(Rewritable.scala:174)
[error] 	at pgo.model.Rewritable$TopDownFirstStrategy$.$anonfun$execute$3(Rewritable.scala:181)
[error] 	at scala.collection.immutable.List.map(List.scala:246)
[error] 	at scala.collection.immutable.List.map(List.scala:79)
[error] 	at pgo.model.Rewritable$.transformSubNodes(Rewritable.scala:160)
[error] 	at pgo.model.Rewritable$TopDownFirstStrategy$.execute(Rewritable.scala:181)
[error] 	at pgo.model.Rewritable$TopDownFirstStrategy$.$anonfun$execute$2(Rewritable.scala:176)
[error] 	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
[error] 	at scala.collection.immutable.List.prependedAll(List.scala:156)
[error] 	at scala.collection.immutable.List$.from(List.scala:651)
[error] 	at scala.collection.immutable.List$.from(List.scala:648)
[error] 	at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:42)
[error] 	at scala.collection.IterableOnceOps.toSeq(IterableOnce.scala:1263)
[error] 	at scala.collection.IterableOnceOps.toSeq$(IterableOnce.scala:1263)
[error] 	at scala.collection.AbstractIterator.toSeq(Iterator.scala:1288)
[error] 	at pgo.model.Rewritable.withChildren(Rewritable.scala:101)
[error] 	at pgo.model.Rewritable.withChildren$(Rewritable.scala:100)
[error] 	at pgo.model.mpcal.MPCalNode.withChildren(AST.scala:7)
[error] 	at pgo.model.Rewritable.mapChildren(Rewritable.scala:92)
[error] 	at pgo.model.Rewritable.mapChildren$(Rewritable.scala:45)
[error] 	at pgo.model.mpcal.MPCalNode.mapChildren(AST.scala:7)
[error] 	at pgo.model.Rewritable$TopDownFirstStrategy$.execute(Rewritable.scala:176)
[error] 	at pgo.model.Rewritable.rewrite(Rewritable.scala:113)
[error] 	at pgo.model.Rewritable.rewrite$(Rewritable.scala:112)
[error] 	at pgo.model.mpcal.MPCalNode.rewrite(AST.scala:7)
[error] 	at pgo.trans.MPCalPCalCodegenPass$.apply(MPCalPCalCodegenPass.scala:327)
[error] 	at pgo.PGo$.run(PGo.scala:134)
[error] 	at pgo.PGo$.main(PGo.scala:224)
[error] 	at pgo.PGo.main(PGo.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 3 s, completed Oct. 11, 2021, 10:31:52 a.m.
```

Attached spec: https://gist.github.com/shayanh/f746283780fa86e98f02f5590d3da0fc

**Comment by fhackett** [comment]
Discussion time: do we _want_ this to compile?

I get that there should either be compiler success or a descriptive error message, but the question is which.

Issue: to compile this correctly requires noticing that the code
```
arr[1][2] := "a";
```
should expand to
```
MP.write(arr[1]) := [MP.read(mp[1]) EXCEPT ![2] = "a"];
```
(notation for mapping macro application is imaginary).

Now, I can implement that, but I'm afraid that the consequences of executing both read and write as part of an assignment (but only sometimes, based on very innocent-looking change, when the assignment implies 1/2 mapping macro assign, 1/2 traditional EXCEPT semantics) would be too confusing.

Would you rather get an error and be told to write the read/write pair more explicitly, or would you rather this Just Works?

**Comment by fhackett** [comment]
No, that's the thing... I can't think of a time when you wouldn't want to clearly annotate reads/writes when they expand specially via MPCal.

You've written more MPCal than me at this point, so back to you: do you have any example when this isn't user error / unintended? (I re-read the issue title, and maybe you don't).

I can always remove the error / make it a compiler flag later, depending.
